name: Pull Request CI/CD

on:
  pull_request:
    branches: [main]
    paths:
      - "Package.swift"
      - "Source/**"
      - "Tests/**"

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run build
        run: swift  build

      - name: Run tests
        run: swift test
