name: Pull Request CI/CD

on: [pull_request, push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: xcodebuild
